name: Hoarders Heir
favicon: null
layout_spectrum: 0.4854715436231345
typography_spectrum: 0.011541927000507712
title: "Hoarder's Heir  ♕ A Prop Duo"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2d353c'
    - '#af986e'
    - '#585e63'
    - '#afb3b6'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.8492020086850971
purpose: []
